- name: Reconnecting Machine
  hosts: scanners
  gather_facts: true
  become: true
  become_method: runas
  become_user: svc.auto_user
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore


    tasks:
    - name: Check if Windows machine is reachable
      become: yes
      win_service:
        name: WinRM
        state: started
