- name: Restart Machine
  hosts: scanners
  gather_facts: true
  become: true
  become_method: runas
  become_user: user
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore


  tasks:
  -   name: Restart Machine
      become: true
      win_command: shutdown /r /t 0
  tags:
    - restart
