
- name: Warn logged in users of impending upgrade
  win_msg:
    display_seconds: 12
    msg: Importing Shell Registry.
    tags:
      - Autologin

- name: Checking if autologin_svc_auto.reg exists
  win_stat:
    path: 'C:\temp\shell.reg'
  register: autologin
  tags:
    - Autologin

- name: Copying autologin_svc_auto.reg
  win_command: xcopy "C:\Users\Auto\Downloads\shell.reg" C:\temp
  when: not autologin.stat.exists
  tags:
    - Autologin

- name: Importing autologin_svc_auto registry file
  ansible.windows.win_command:
    cmd: reg import "C:\temp\shell.reg"
  tags:
    - Autologin
