
- name: VC Build tools
  win_command: xcopy "\\dataFiles\Files\vs_BuildTools.exe" C:\Installations/E /H /I
  tags:
    - vs_build_tools

- name: Install VC Build tools
  ansible.windows.win_package:
    path: "C:\\Installations\\vs_BuildTools.exe"
    arguments: "--quiet --wait --includeRecommended --add Microsoft.VisualStudio.Workload.VCTools "
    state: present
  become: true
  tags:
      - vs_build_tools
