
- name: Create GitRep folder
  ansible.builtin.win_file:
     state: directory
     recurse: true
     path: C:\GitRep
     tags:
       - git

- name: Installing Chocolatey
  raw: |
    Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  become: true
  ignore_errors: yes
  tags:
    - git

- name: Installing git
  win_chocolatey:
    name: git
    state: present

- name: Cloning Git repository team
  win_shell: git clone ssh://sna/team.git C:\\GitRep\\skynet
  become: yes
  tags:
     - git

- name: Running poetry install on team
  win_command: poetry install
  args:
    chdir: C:\GitRep\skynet
  ignore_errors: yes
  tags:
    - git

- name: Cloning Git repository team2
  win_shell: git clone ssh://sna/team2.git C:\\GitRep\\aurora
  become: yes
  tags:
    - git

- name: Running poetry install on team2
  win_command: poetry install
  args:
    chdir: C:\GitRep\aurora
  ignore_errors: yes
  tags:
    - git


- name: Setting WORK_DIR environment variable for Git
  win_environment:
    name: WORK_DIR
    value: "C:\\GitRep"
    state: present
    level: user
  tags:
#    - git
