- name: Create WINRM folder
  ansible.builtin.win_file:
    state: directory
    recurse: true
    path: C:\WINRM
  tags:
    - WinrmService

- name: Copying Winrm batch to C:\
  win_command: xcopy "\\dataFiles\Ido Saraf\WINRM" C:\WINRM /E /H /I
  ignore_errors: yes
  tags:
    - WinrmService


- name: Copying Winrm batch to startup
  win_command: xcopy "C:\WINRM\Enable.bat - Shortcut.lnk" "C:\\Users\\svc.auto_user\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup" /E
  ignore_errors: yes
  tags:
    - WinrmService

- name: Copying Winrm batch to startup
  win_command: xcopy "C:\WINRM\Enable.bat - Shortcut.lnk" "C:\\Users\\cvsrnd\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup" /E
  ignore_errors: yes
  tags:
    - WinrmService

