
- name: Warn logged in users of impending upgrade
  win_msg:
    display_seconds: 12
    msg: Automated upgrade about to start.
    tags:
      - common

- name: Create Installations For Skynet folder
  ansible.builtin.win_file:
    state: directory
    recurse: true
    path: C:\InstallationsForSkynet
    tags:
      - common

- name: Checking if autologin_svc_auto.reg exists
  win_stat:
    path: 'C:\temp\autologin_svc_auto.reg'
  register: autologin
  tags:
    - common

- name: Copying autologin_svc_auto.reg
  win_command: xcopy "\\data\Users\automation\scripts\autologin_svc_auto.reg" C:\temp
  when: not autologin.stat.exists
  tags:
    - common

- name: Importing autologin_svc_auto registry file
  ansible.windows.win_command:
    cmd: reg import "C:\temp\autologin_svc_auto.reg"
  tags:
    - common

- name: Checking if shell exists
  win_stat:
    path: 'C:\temp\shell.reg'
  register: shell
  tags:
    - common

- name: Copying shell.reg
  win_command: xcopy "\\data\Automation\FARM\Files\shell.reg" "C:\temp /E /H /I
  when: not shell.stat.exists
  tags:
    - common

- name: Importing shell registry file
  ansible.windows.win_command:
    cmd: reg import "C:\temp\shell.reg"
  tags:
    - common

- name: Checking if .ssh folder exists
  win_stat:
    path: 'C:\Users\svc.auto_user\.ssh'
  register: ssh_folder
  tags:
    - common

- name: Copy .ssh folder
  win_command: xcopy "\\data\Automation\FARM\Files\Skynet setup\.ssh" "C:\Users\svc.auto_user\.ssh" /E /H /I
  when: not ssh_folder.stat.exists
  tags:
    - common

- name: Checking if Robocopy Already exists in C
  win_stat:
    path: 'C:\robocopy-automation.rcj'
  register: robocopy
  tags:
    - common

- name: Copying Robocopy
  win_command: xcopy "\\data\Users\Ido Saraf\robocopy-automation.rcj" C:\
  when: not robocopy.stat.exists
  tags:
    - common

- name: Copying Rules.reg for FireWall
  win_command: xcopy "\\data\Users\Ido Saraf\rules.reg" C:\temp
  ignore_errors: yes
  tags:
    - common

- name: Importing Rules registry file
  ansible.windows.win_command:
    cmd: reg import "C:\temp\rules.reg"
  tags:
    - common


