
- name: Coping npp.8.4.7.Installer.x64.exe
  win_command: xcopy "\\data\Files\\npp.8.4.7.Installer.x64.exe" C:\Installations /E /H /I
  tags:
    - Notepad++

- name: Installing Notpad++
  ansible.windows.win_package:
    path: 'C:\\Installations\\npp.8.4.7.Installer.x64.exe'
    arguments: "/quiet /S"
    state: present
  tags:
    - Notepad++

- name: Removing The exe File
  ansible.windows.win_file:
    path: 'C:\\Installations\\npp.8.4.7.Installer.x64.exe'
    state: absent
    tags:
      - Notepad++

